# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 197a29276a332fae9db9987b70529cd8e6739517d3bba913645ac9383b1146530e987ef8a182339fad97ac2fe21a04773860fe0d89d60a80634a5bc60bfbab55

test:
  secret_key_base: 1f8fdf59d35461bb8a47251057add7d02eabef687af26273a0b25b5feb256a97ba7aa6b96378a20ef9647d23fc2a748f1d9762edc51a3a116cc0cfaafc08c698

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
